spring:
  datasource:
    name: xa-datasource
    url: # resolved by test containers
    username: # resolved by test containers
    password: # resolved by test containers

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect



logging.level.org.springframework.transaction: DEBUG
logging.level.com.atomikos: DEBUG


server:
  shutdown: graceful

service:
  jta:
    jms:
      destination: jta-queue
